name: Notify Monorepo
  on:
    push:
      branches: ['main']
  jobs:
    notify:
      runs-on: ubuntu-latest
      steps:
        - name: Debug token
          run: |
            echo "GH_TOKEN: ${{ secrets.GH_TOKEN != '' && 'set' || 'not set' }}"
        - name: Trigger monorepo workflow
          env:
            GH_TOKEN: ${{ secrets.GH_TOKEN }}
          run: |
            curl -X POST \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: Bearer $GH_TOKEN" \
              https://api.github.com/repos/stocktaking-inc/inventory-monorepo/dispatches \
              -d '{"event_type": "submodule_updated", "client_payload": {"submodule": "auth-frontend"}}'
